const USER_ROLES = Object.freeze({
  ADMIN: "ADMIN",
  RECEPTIONIST: "RECEPTIONIST",
  PATIENT: "PATIENT",
  DOCTOR: "DOCTOR",
});

const APPOINTMENT_STATUS = Object.freeze({
  BOOKED: "BOOKED",
  CHECKED_IN: "CHECKED_IN",
  IN_QUEUE: "IN_QUEUE",
  CALLED: "CALLED",
  IN_CONSULTATION: "IN_CONSULTATION",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
});

const QUEUE_STATUS = Object.freeze({
  OPEN: "OPEN",
  PAUSED: "PAUSED",
  CLOSED: "CLOSED",
});

const QUEUE_ENTRY_STATUS = Object.freeze({
  WAITING: "WAITING",
  SKIPPED: "SKIPPED",
  CALLED: "CALLED",
  IN_SERVICE: "IN_SERVICE",
  DONE: "DONE",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
});

const PRIORITY_LEVEL = Object.freeze({
  EMERGENCY: "EMERGENCY",
  SENIOR: "SENIOR",
  PREGNANT: "PREGNANT",
  VIP: "VIP",
  NORMAL: "NORMAL",
});

module.exports = {
  USER_ROLES,
  APPOINTMENT_STATUS,
  QUEUE_STATUS,
  QUEUE_ENTRY_STATUS,
  PRIORITY_LEVEL,
};
